### PR TITLE
Deprecation fixes for Julia 0.7

### PR DESCRIPTION
**Pull request by martinholters**
This requires https://github.com/JuliaLang/Compat.jl/pull/481 which I have tentatively assumed to be included in a future Compat 0.52. (Tests will fail immediately due to Compat 0.52 not being available, yet).

### CODE REVIEW

**Comment by martinholters** [comment]
Retrigger CI...

**Comment by martinholters** [comment]
Good to go from my side.

**Comment by martinholters** [comment]
Objections against tagging 0.5.4?

**Comment by timholy** [comment]
None, I should have done that earlier. Give your new powers a try :smile:.

**Pull request merged**
