### PR TITLE
Fix deprecation: tty_size -> displaysize

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by garrison** [comment]
This should have a `VERSION` check, since `Base.displaysize` does not exist in 0.4

**Comment by Keno** [comment]
It does exist in Compat and is exported.

**Comment by Keno** [comment]
Looks like the compat wrapper is broken. `displaysize` takes and argument while tty_size does not.

**Comment by garrison** [comment]
In that case, I think you should call `displaysize`, not `Base.displaysize`, so that `Compat` can cover on julia 0.4.  But the compat wrapper will need fixed too, as you mention.

**Comment by Keno** [comment]
Yes, you're right. I meant to do that. Sorry!

**Comment by timholy** [comment]
Superseded by #39.

**Pull request closed without merging**
