### PR TITLE
Change default IJulia behaviour

### PR DESCRIPTION
**Pull request by saschatimme**
This resolves the problem described in #162.

### CODE REVIEW

**Comment by xukai92** [comment]
As it was explained in https://github.com/timholy/ProgressMeter.jl/pull/147#issuecomment-614663105, the reason the default is warning is because this behaviour can sliently clear other possible outputs in the cell. Changing the default in ProgressMeter seems dangerous to me. In my opinion, either the package that uses ProgressMeter could export ProgressMeter (so that users could do the change of default as suggested by warning), or the default should be changed only within that package.

**Comment by saschatimme** [comment]
I am aware that this clears other fields. But this is about trade offs and I think the much better trade off is to just clear things by default.

**Comment by zsunberg** [comment]
Ugh, this is a really annoying case... It could be catastrophically confusing to someone if they have debug print statements that they don't see.

Perhaps here are a few alternate things to try:
1. Can we detect if the user has printed things? (e.g. by checking if there are more lines in the output cell than we have printed) We could not clear in that case.
2. Would it be possible to change the warning to be one line that is printed above the progress bar so that it is not so intrusive?

**Comment by timholy** [comment]
Would it be OK to print the warning only once?

I'm not an IJulia user so I'll leave it up to others to decide.

**Comment by xukai92** [comment]
I guess printing it only for the first time sounds the best compremise and is also doable using similar tricks here in JuliaGPU for `allowscalar`: https://github.com/JuliaGPU/GPUArrays.jl/blob/fa6e0b3ea24b4931b3223e858133f90cf019b5b8/src/host/indexing.jl#L21

**Comment by timholy** [comment]
I'd support that change.

**Comment by IanButterworth** [comment]
I didn't mean to rebase this branch. But while I'm here, can someone decide if this is good to go? (I don't use IJulia)

**Comment by xukai92** [comment]
> I guess printing it only for the first time sounds the best compremise and is also doable using similar tricks here in JuliaGPU for `allowscalar`: https://github.com/JuliaGPU/GPUArrays.jl/blob/fa6e0b3ea24b4931b3223e858133f90cf019b5b8/src/host/indexing.jl#L21

This change doesn't seem to be implemented.

**Pull request closed without merging**
