### PR TITLE
map and pmap to fix #32

### LINKED ISSUE #32: Working with pmap
I thought I should note here that I found working with pmap and ProgressMeter a bit tricky, so I bundled the solution as a very simple package: https://github.com/slundberg/PmapProgressMeter.jl which provides `pmap(p::Progress, f::Function, values)`.

This is related to #9 and it may be of interest to eventually merge this into ProgressMeter.

### PR DESCRIPTION
**Pull request by zsunberg**
This PR will add support for both `map` and `pmap`

Primary usage will be through `@showprogress`, e.g.
```julia
@showprogress pmap(x->x^2, 1:10)
```

I have implemented the `progress_map` function, which uses channels to pass progress information back to the main process that prints the progress meter. It works for both `map` and `pmap`. Now I just need to modify `showprogress` to convert `map` and `pmap` calls into `progress_map` calls.

Comments welcome.

### CODE REVIEW

**Comment by zsunberg** [comment]
Ok, I think this is nearly ready to merge.

There is one problem - currently ProgressMeter has to be loaded on all processes for this to work. I believe this is because the anonymous function defined on [line 575](https://github.com/zsunberg/ProgressMeter.jl/blob/8a7d885a82337c38d815d436e6e01ea18e5a42ff/src/ProgressMeter.jl#L575) apparently is defined only in the ProgressMeter module. I am not sure how to fix it.

I have put a fair amount of effort into creating concise code that works in all the cases I could think of, so I hope it can get merged soon :)

**Comment by djsegal** [comment]
Is this like a cruel joke? I don't really care if it's perfect, but can we push something that's v0.7 compatible?

It seems like:

+ https://github.com/slundberg/PmapProgressMeter.jl

works perfectly in every place I've ever used it?

**Comment by zsunberg** [comment]
Not sure what the cruel joke is - this PR is v0.7 compatible. Just need a maintainer to merge it @timholy . I think there might be another package that uses the builtin julia logging that people are switching to.

**Comment by zsunberg** [comment]
@garrison are you the right one to ask to merge this?

**Comment by timholy** [comment]
Sorry for the unconscionable delay, I have too many packages that I maintain and need to ditch responsibility for some. I'll give more people rights to this one.

**Comment by timholy** [comment]
Turns out there were 5 people already authorized to merge PRs here, but I added you too @zsunberg.

**Pull request merged**
