### PR TITLE
Allow pipes after a map

### PR DESCRIPTION
**Pull request by fredcallaway**
Adresses #177

### CODE REVIEW

**Review by timholy — APPROVED** [review]
I'll leave this open in case anyone else wants to review it. If no complaints have emerged in a couple of days, let's merge this. (If I forget, please bump.)

**Comment by fredcallaway** [comment]
My first contribution to a Julia package! :)

**Comment by timholy** [comment]
And a very fine one indeed!

**Comment by timholy** [comment]
It's already out in the wild, too: version 1.4.1 was released earlier today with this change. Nice feeling, isn't it?

**Pull request merged**
