### PR TITLE
Added ability to show 0 progress and reset progress bar.

### PR DESCRIPTION
**Pull request by ry-dgel**
As per #86, an error occurs when update!(p, 0) is run. This comes up due to an attempt to round an infinite eta time.

I've fixed this issue by adding a modified version of `durationstring()` that takes in a nullable, and will output "N/A" if the eta time is null. Coupled with this, `updateProgress!` now uses a nullable for `eta_sec` which will be set to null if `percentage_complete == 0`.

For a simulation that I'm working on, each step takes quite some time, so I was looking for a way to show the bar with 0% progress to at least indicate the the simulation had started. So, I added the `start!()` function which does exactly this. This function can also be used to restart a progress bar, resetting the timing and counter.

This is also my first ever pull-request and contribution to a public project, let me know how I did!

### CODE REVIEW

**Comment by ry-dgel** [comment]
Travis is upset with my code not working on 0.7 builds. As I don't have 0.7 setup and running I can't immediately fix these issues in a cross compatible way, but for a 0.7 version it'll be simple to change to using Union{Some(T), Nothing} where T<:Number.

**Comment by martinholters** [comment]
I'm not sure the introduction of a `Nullable` and the change to `durationstring` is needed here. Setting `eta = "N/A"` directly in `updateProgress!` should be ok. Alternatively, pull the definition of `msg` into the `if`/`else` and completely leave out the `ETA:` part if `iszero(percentage_complete)`. Personally I think I'd prefer the latter.

**Comment by timholy** [comment]
Thanks for your contribution, @ry-dgel, and sorry I didn't react to your first public pull request! I've been really swamped the last few months.

Given the long latency, I can take it from here or coach you through it. Which would you prefer? I created the branch that become #98 before realizing this was here.

**Comment by timholy** [comment]
I'm going to go ahead and merge #98. That doesn't fix the "show 0% progress" issue (tricky because when the computation is fast, you generally don't want to show any progress bar), so I'd be happy to entertain a PR focused on that issue.

**Pull request closed without merging**
