### PR TITLE
Allow to opt-in into clearing IJulia cell

### PR DESCRIPTION
**Pull request by saschatimme**
This add the possibility to clear output of IJulia cells to get a behaviour similar to the REPL. 
The difference to #93 is that this behaviour is completely optional **and** you have to opt-in into this behaviour. I think we should let make the end user the call whether he wants this behaviour or not while providing by default the safe choice.

Here is a video of the old and the new behaviour:
https://www.youtube.com/watch?v=nO8N1Cda0FA

### CODE REVIEW

**Comment by zsunberg** [comment]
This seems ok to me - it is only needed when you use stdout though, right? I think the documentation should reflect this.

**Comment by zsunberg** [comment]
Oh, I see - it is only in the presence of showvalues. Why does it work correctly when there are no showvalues? Because it only has to delete one line?

Is it possible to automatically detect whether the user has printed something else? If that is possible, we could include this behavior automatically if nothing else is printed.

**Comment by findmyway** [comment]
Is it possible to have this feature merged?

**Comment by timholy** [comment]
> Is it possible to have this feature merged?

Yes. But it would be great to have @saschatimme respond to @zsunberg's questions. I don't think we have to get the automatic part implemented in this PR, though.

**Comment by arnavs** [comment]
Thanks for this @saschatimme; ended up using this in my own work just now.

**Comment by xukai92** [comment]
> Why does it work correctly when there are no showvalues?

There was some explanations here https://github.com/timholy/ProgressMeter.jl/issues/71#issuecomment-379222272

> Is it possible to automatically detect whether the user has printed something else? If that is possible, we could include this behavior automatically if nothing else is printed.

There is. Basically we only need to trigger it when `showvalues` is not empty for IJulia. But I think the idea of this PR is to make this IJulia clear output behaviour explict rather than automatic.

I'm also looking forward to have this feature merged :)

**Comment by xukai92** [comment]
As a note, one way to automate this is by the following
```julia
function ProgressMeter.move_cursor_up_while_clearing_lines(io::Main.IJulia.IJuliaStdio, numlinesup::Int)
    if numlinesup > 0 && isdefined(Main, :IJulia) && Main.IJulia.inited
        Main.IJulia.clear_output(true)
    end
end
```
We can load this one when IJulia is defined using Requires.jl

**Comment by xukai92** [comment]
Also, the current way to make it optional is by set the behaviour when creating the progress bar and passing the keyword agurment through all the functions. Wouldn't it be better to deal with this option in a package level? We can do something like below

```julia
const is_clearijulia = Ref(false) # off by default
clearijulia(flag=false) = (is_clearijulia[] = flag)
```

Users can create the progree bar as usual and turn this on and off by `clearijulia(true)` or `clearijulia(false)` globally.

**Pull request merged**
