### PR TITLE
counterfirst

### PR DESCRIPTION
**Pull request by gustafsson**
I'd like to be able to specify where the progress meter should start so that I can continue a long-running process that is already half-finished.

### CODE REVIEW

**Comment by martinholters** [comment]
Should be documented.

An alternative API could be something like `pause!(p)`/`resume!(p)`, so that the ETA would be based on the time spent before and after the pause, but not during. Not totally sure I like that better, though.

**Comment by gustafsson** [comment]
Naming things is hard. I renamed `conterfirst` to `resumefrom` and added some documentation.

The idea with this PR I intend to cover the case when the process was killed and then resumed at a later point, so there wouldn't be a previously paused instance of `Progress` to call with `resume!`.

As a side effect I think this interface could also be used for use case of pause/resume. Though the user would have to deal with what they want their output to look like during the "pause".

**Comment by martinholters** [comment]
I do like `resumefrom` better than `counterfirst`. And you're right, of course, for the killed process scenario, my proposal of `pause`/`resume` wouldn't cut it.

**Comment by martinholters** [comment]
LGTM and I've resolved the conflicts, but would like to hear @timholy's opinion.

**Comment by timholy** [comment]
Sorry for the absence here. This is a good idea.

As you say, naming is probably the hardest bit. Is there any reason not to call it `start`? For example, here's the julia 0.7 docstring for `range`:
```julia
  range(start; length, stop, step=1)
```
where either `length` or `stop` must be specified. Consistent with this, I wonder if we should call this keyword `start`?

**Comment by timholy** [comment]
Needs to pass tests before it can be merged.

**Comment by timholy** [comment]
Thanks @gustafsson!

**Pull request merged**
