### PR TITLE
ProgressMeter v1.10.0

### PR DESCRIPTION
**Pull request by IanButterworth**
I'll leave this up for a day in case anyone thinks this should be a minor bump (all the commits looked like fixes to me)

### CODE REVIEW

**Comment by MarcMush** [comment]
I think #284 at least requires a minor bump

**Comment by IanButterworth** [comment]
Hm good point, but that appears to be undocumented? no docstring, no mention in the readme?

**Comment by IanButterworth** [comment]
Oh. I misread the `showprogressthreads` function as the API.  If this is making `@showprogress Threads.@threads for ...` work then IMO it seems more like a fix than a feature?

**Comment by MarcMush** [comment]
I guess both can be justified
And I would argue that #296 is also a new feature

**Comment by IanButterworth** [comment]
Ok. Let's do a minor bump then. Helps for messaging around the release.

**Comment by IanButterworth** [comment]
https://github.com/JuliaRegistries/General/pull/102242

**Pull request merged**
