### PR TITLE
Fix warnings regarding deprecation of (`immutable`) `type`

### PR DESCRIPTION
**Pull request by martinholters**
It's not pretty, but works...

### CODE REVIEW

**Comment by timholy** [comment]
Is there no Compat solution for this?

**Comment by martinholters** [comment]
Ref. JuliaLang/Compat.jl#338

**Comment by timholy** [comment]
Hmm, interesting issues. I'd almost rather just require 0.6, how do you feel about that?

**Comment by martinholters** [comment]
> It's not pretty

... so no offense taken if you rather not go with this.

**Comment by timholy** [comment]
Closed by #81. Sorry for not taking this!

**Comment by martinholters** [comment]
> Sorry for not taking this!

No worries!

**Pull request closed without merging**
